# config
cover: /img/bg.jpg
logo: /img/favicon.png
top_saying:
- title: Splintered Light Books
- content: With the new day comes new strenght and new thoughts. - Eleanor Roosevelt
bottom_saying: Self-belief and hard work will always earn you success. - Virat Kohli
# Content
excerpt_link: Read More

rss: /atom.xml

highlightjs: vs

#Works
#works:
#- works_name: AAA
#  works_url: /
#- works_name: BBB
#  works_url: /atom.xml

#duoshuo name
duoshuo:

#disqus name
disqus_shortname:

#fancybox
fancybox: true

# Miscellaneous
twitter: https://twitter.com/
facebook: https://www.facebook.com/
google: https://google.com/
weibo: http://weibo.com/

#about  timeline
timeline:
- num: 1
  word: In 2014, Splintered Light Books has been founded
- num: 2
  word: In 2015, receive an Award of Best Writer
- num: 3
  word: In 2017, our site reach 100K subscribes
- num: 4
  word: In 2018, the site designed to a whole new interface

  #Links
#links:
#- name: Kieran
#  link: http://go.kieran.top/
#- name: Name
#  link: http://domain.com/

# Local search
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
  enable: true
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: -1